# MSDS 400 Matrix Operations

In [2]:
from numpy import array, absolute
import numpy as np

**Module Objective:** demonstrate numpy list and array operations.
(Numpy Lists and arrays are useful data structures that serve multiple
purposes. For matrix calculations, arrays must be converted into
matrices. Array manipulations are valuable for preparing data for
linear algebra. Matrix calculations are shown in Session 2 Module 3.

This example defines a list called t, and shows how elements 1 and 3
can be located.  The first element in t is indexed as 0.

In [10]:
t = [1, 2, 3]
print('\nValue at first location:  {}'.format(t[0]))
print('Value at third location:  {}'.format(t[2]))
print('Value located using negative index:  {} \n'.format(t[-2]))


Value at first location:  1
Value at third location:  3
Value located using negative index:  2 



The next two examples demonstrate the difference between concantenation
and forming an array. `result2` is a list of lists or an array.

In [11]:
print('Comparison of a concatenated list with an array ')
r = [4, 5, 6]
print('r= {} and t= {} \n'.format(r, t))
result1 = t + r
print('Concatenation example using t and r lists. {}'.format(result1))
result2 = array([t, r])
print('\n Comparison of concatenation with array([t,r]).')
print(result2)

Comparison of a concatenated list with an array 
r= [4, 5, 6] and t= [1, 2, 3] 

Concatenation example using t and r lists. [1, 2, 3, 4, 5, 6]

 Comparison of concatenation with array([t,r]).
[[1 2 3]
 [4 5 6]]


**Note:** Different results are produced by indexing for a list and an array.

In [12]:
print('\n The second element of the preceding list and array')
print(result1[1])
print(result2[1])


 The second element of the preceding list and array
2
[4 5 6]


Array slicing is demonstrated briefly with two examples.  The first shows
how to produce a single element.  The second and third show how to produce
a reduced array from the original array. Array slicing goes beyond the
scope of this course.  It is an essential tool for array operations.

In [13]:
print('\n Slicing to produce an element, a column and a row of the array')
print(result2[0, 1])
print(result2[:, 1])  # Note the horizontal output of a column.
print(result2[1, :])


 Slicing to produce an element, a column and a row of the array
2
[2 5]
[4 5 6]


The next series of examples demonstrates simple array operations.  Arrays may
be operated on prior to conversion to a matrix for matrix operations.
Arrays can be constructed directly from lists of data.

In [14]:
m = array([[10, 12, 5], [15, 20, 8]])
n = array([[45, 35, 20], [65, 40, 35]])
q = m + n
print('\n Arrays in order: m , n and m+n')
print(m)
print(n)  # Note that context determines the purpose of "n".
print(q)

print('\n Subtraction of n from m equals q')
q = m - n
print(q)

s = 2.0
print('\n Multiplication of q by a scalar {}'.format(s))
q = s*q
print(q)

print('\n Functions can be applied to an array such as absolute value')
q = absolute(q)
print(q)


 Arrays in order: m , n and m+n
[[10 12  5]
 [15 20  8]]
[[45 35 20]
 [65 40 35]]
[[55 47 25]
 [80 60 43]]

 Subtraction of n from m equals q
[[-35 -23 -15]
 [-50 -20 -27]]

 Multiplication of q by a scalar 2.0
[[ -70.  -46.  -30.]
 [-100.  -40.  -54.]]

 Functions can be applied to an array such as absolute value
[[ 70.  46.  30.]
 [100.  40.  54.]]


In [3]:
A = np.array([[1, 1, 1], [12,17,22], [15,22,38]])
b = np.array([165, 3055, 4700])
x = np.linalg.solve(A, b)

print(x)

[30. 55. 80.]


In [4]:
A = np.array([[.2,.15,.15], [.3,.5,.2], [.5,.35,.65]])
b = np.array([90400, 190300, 272300])

x = np.linalg.solve(A, b)
print(x)

[149000. 216000. 188000.]


In [6]:
import numpy as np
A = np.array([[12000,23000,35000,52000],[15000,21000,28000,60000]])
B = np.array([[0.08, 0, 0,0], [0, 0.13,0,0], [0,0,0.07,0], [0,0,0,0.2]])
print(A)
print(B)
result = np.matmul(A, B)
print(result)


[[12000 23000 35000 52000]
 [15000 21000 28000 60000]]
[[0.08 0.   0.   0.  ]
 [0.   0.13 0.   0.  ]
 [0.   0.   0.07 0.  ]
 [0.   0.   0.   0.2 ]]
[[  960.  2990.  2450. 10400.]
 [ 1200.  2730.  1960. 12000.]]


Below is calculating cramers rule for a system of equations of 2 equations.

In [9]:
import numpy as np

def cramer(mat, constant):
    D = np.linalg.det(mat)
    mat1 = np.array([constant, mat[:, 1]])
    mat2 = np.array([mat[:, 0], constant])
    Dx = np.linalg.det([mat1, mat2])
    X = Dx/D
    return X, D, Dx

A = np.array([[4,-2], [3, -1]])
b = np.array([-2, -4])

x = cramer(A, b)
print(x)





(array([-3., -5.]), 2.0, array([ -6., -10.]))


for a system of three equations: 

In [3]:
def cramer(mat, constant):
    D = np.linalg.det(mat)
    mat1 = np.array([constant, mat[:, 1], mat[:, 2]])
    mat2 = np.array([mat[:, 0], constant, mat[:, 2]])
    mat3 = np.array([mat[:, 0], mat[:, 1], constant])
    Dx = np.linalg.det([mat1, mat2, mat3])
    X = Dx/D
    return X, D, Dx

A = np.array([[.2,.15,.15], [.3,.5,.2], [.5,.35,.65]])
b = np.array([90400, 190300, 272300])

x = cramer(A, b)
print(x)

(array([149000., 216000., 188000.]), 0.01500000000000001, array([2235., 3240., 2820.]))
