# MSDS 400 Matrix Inverses

In [2]:
import numpy as np
from numpy.linalg import linalg, inv

**Module Objective:** demonstrate numpy matrix calculations.  For
matrix calculations, arrays must be converted into numpy matrices.

With numpy matrices, you can add, subtract, multiply, find the transpose
find the inverse, solve systems of linear equations and much more.

Solve a system of consistent linear equations.

Right hand side of system of equations has data entered as a list
and converted to 3x1 matrix and then a 1x3 matrix using the transpose
function. Similar steps are taken for the matrix A.

In [4]:
# rhs = [96, 87, 74]
# rhs = np.matrix(rhs)
# rhs = np.transpose(rhs)
# print('\nRight Hand Side of Equation')
# print(rhs)

A = [[1, -6,2], [0, -8 , 3], [0,-3,1]]
A = np.matrix(A)
print('\nMatrix A')
print(A)


Matrix A
[[ 1 -6  2]
 [ 0 -8  3]
 [ 0 -3  1]]


Numpy has various functions to perform matrix calculations.  The inverse
function inv() is one of those.

Find inverse of A.

In [5]:
print('\nInverse of A')
IA = inv(A)
print(IA)


Inverse of A
[[ 1.  0. -2.]
 [-0.  1. -3.]
 [-0.  3. -8.]]


In what follows, I am converting matrices with floating point numbers  to
matrices with integer numbers.  This is optional and being done to show
that it is possible to do so with numpy matrices.

Note that the function np.dot() performs matrix multiplication.
Verify inverse by multiplying matrix A and its inverse IA.

In [5]:
print('\nIdentity Matrix')
I = np.dot(IA, A)
I = np.rint(I)               # This converts floating point to integer.
print(I)


Identity Matrix
[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Solve the system of equations and convert to integer values. With numpy it is necessary to use np.dot() for the product.

In [8]:
result = np.dot(IA, rhs)
result = np.rint(result)    # This converts floating point to integer.
print('\n Solution to Problem')
print(result)


 Solution to Problem
[[13.]
 [ 1.]
 [20.]]


**Note:** There is a more efficient way to do this with the linalg.solve() function.

In [9]:
print('\Illustration of solution with linalg.solve(,) function')
result2 = linalg.solve(A, rhs)
print(np.rint(result2))    # This converts floating point to integer.


Illustration of solution with linalg.solve(,) function
[[13.]
 [ 1.]
 [20.]]


Some square matrices do not have inverses. The following example shows
how this is handled with numpy.  Note the magnitude of the elements.

In [3]:
print('\nExample of an inverse matrix for inconsistent equations')
A = [[1, 2, 3], [-3, -2, -1], [-1, 0, 1]]
A = np.array(A)
IA = inv(A)
print(IA)
print(A)


Example of an inverse matrix for inconsistent equations
[[-2.25179981e+15 -2.25179981e+15  4.50359963e+15]
 [ 4.50359963e+15  4.50359963e+15 -9.00719925e+15]
 [-2.25179981e+15 -2.25179981e+15  4.50359963e+15]]
[[ 1  2  3]
 [-3 -2 -1]
 [-1  0  1]]


In [9]:
A = np.array([[.65,.6,.95], [.35,.4,.05]])
B = np.array([[8,15], [5,5], [29,26]])
C = np.matmul(A, B)
print(A)
print(B)
print(C)

[[0.65 0.6  0.95]
 [0.35 0.4  0.05]]
[[ 8 15]
 [ 5  5]
 [29 26]]
[[35.75 37.45]
 [ 6.25  8.55]]


SOlve system of equations where the answer (Right hand is B= -1, 2)

In [10]:
A = np.array([[5,-25],[-1,7]])
B = np.array([-1,2]) #right hand of equations
# IA = inv(A)
# print(IA)
# print(A)
result2 = linalg.solve(A, B)
print(result2)



[4.3 0.9]


Solve system of equations with three equations and three responses. 

In [11]:
A = np.array([[41,4,26],[0,6,66],[4,24,25]])
B = np.array([191,156,158]) #right hand of equations
# IA = inv(A)
# print(IA)
# print(A)
result2 = linalg.solve(A, B)
print(result2)

[3. 4. 2.]
